#!/usr/bin/env ruby -wKU
#parser.rb

#Constants
Lookarry = %w[l look]
Movearry = %w[go move]
NilResponce = 'Im sorry, could you speak up?'
NoGoResponce = 'You cannot go that way.'
NilGoResponce = 'Which way did you want to go?'

class Parser
	public
	def parse(command, currentRoom)
		command.downcase!
		if command == 'quit' then
			exit
		else
			cd1, cd2, cd3 = command.split(" ")
		end

		if cd1 == nil then
			puts NilResponce
		end
		
		if Lookarry.include? cd1 then #user wants to look
			if cd2 == nil  then
				puts currentRoom.description
			elsif cd2 == 'at'
				cd1 = 'examine'
				cd2 = cd3
			elsif cd2 == 'around'
				puts currentRoom.description
			else
				puts "I'm sorry, I dont know what you mean by look #{cd2}"
			end
		end
		if Movearry.include? cd1 then #user wants to move, check if it matches available directions
			if cd2 != nil then
				if currentRoom.directions.include? cd2 then #user cannot go that way
					puts 'You can go that way.' #temp
				else
					puts NoGoResponce
				end
			else
				puts NilGoResponce
			end
		end
		if cd1 == 'examine' then
			command.delete "the"

			needPass = true
			currentRoom.items.each do |item|
				if item.name == cd2 then
					puts item.description
					needPass = false
					break
				end
			end
			if needPass
				if cd2 == nil then
					puts 'Examine what?'
				else
					puts "There is no #{cd2}"
					return
				end
			end
		end
	end
end